apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: threat-scanning-webhook-cert
  namespace: threat-scanning-system
spec:
  secretName: threat-scanning-webhook-certs
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
    - trilio
  commonName: threat-scanning-webhook-service.threat-scanning-system.svc
  dnsNames:
  - threat-scanning-webhook-service
  - threat-scanning-webhook-service.threat-scanning-system
  - threat-scanning-webhook-service.threat-scanning-system.svc
  - threat-scanning-webhook-service.threat-scanning-system.svc.cluster.local
  issuerRef:
    name: threat-scanning-selfsigned-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: threat-scanning-selfsigned-issuer
  namespace: threat-scanning-system
spec:
  selfSigned: {}
