apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: threat-scanning
    app.kubernetes.io/part-of: threat-scanning
  name: trilio-threat-scanning
  namespace: default

