apiVersion: threatscanning.trilio.io/v1
kind: Target
metadata:
  name: minio-target-1
spec:
  targetType: TVK
  type: ObjectStore
  vendor: Other
  objectStoreCredentials:
    url: https://api.minio.k8strilio.net
    region: us-east-1
    bucketName: dipayan2
    credentialSecret:
      name: minio-target-secret
      namespace: default
    skipCertVerification: true
  thresholdCapacity: 100Gi