apiVersion: v1
kind: Secret
metadata:
  name: minio-target-secret
  namespace: default
type: Opaque
stringData:
  accessKey: TRILIOMINIO
  secretKey: HAAMAALUMHAICHALNA
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-local-secret
  namespace: default
type: Opaque
stringData:
  accessKey: ROOTNAME
  secretKey: CHANGEME123